import { Html, Head, Main, NextScript } from "next/document";
import Script from "next/script";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Shantell+Sans:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />

        <title>Portfolio\ExeDev</title>
      </Head>
      <body>
        <Script
          src="https://kit.fontawesome.com/ef487b269e.js"
          crossorigin="anonymous"
          strategy="beforeInteractive"
        ></Script>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
